### ISSUE TITLE
how to generate mAP for training dataset?

### ISSUE THREAD

**Issue by IamExperimenting** [sayakpaul/Blood-Cell-Detection-using-TFOD-API#1]
Hi @sayakpaul , Thanks very much for sharing your repository. I have noticed that you have put the tensorboard graph during your presentation. I would like to get some suggestions from you. 

1. how do we get the training metrics like mAP value for every 100 epochs?
2. how to pass the validation data while training the model, so we can see how well the model perform with validation data?

It would be helpful you can provide us with some information.

Thanks very much :)

**Comment by sayakpaul** [comment]
With the approach I have taken with the TFOD API, I don't think there's too much flexibility in doing that. However, I'd suggest you look into the latest examples of the API here: https://github.com/tensorflow/models/tree/master/research/object_detection.
